#ifndef _INCLUDED_neurongroup_1_spike_thresholder_codeobject_after
#define _INCLUDED_neurongroup_1_spike_thresholder_codeobject_after

void _after_run_neurongroup_1_spike_thresholder_codeobject();

#endif
