#ifndef _INCLUDED_neurongroup_spike_thresholder_codeobject_2_after
#define _INCLUDED_neurongroup_spike_thresholder_codeobject_2_after

void _after_run_neurongroup_spike_thresholder_codeobject_2();

#endif
