#ifndef _INCLUDED_synapses_5_synapses_create_generator_codeobject
#define _INCLUDED_synapses_5_synapses_create_generator_codeobject

void _run_synapses_5_synapses_create_generator_codeobject();


#endif
